services:
  controller:
    image: notebookum-controller:v1.2.0
    restart: unless-stopped
    networks:
      notebookum-network:
        aliases:
          - api.universidad.localhost
    environment:
      CONSUL_URL: "http://consul:8500"

networks:
  notebookum-network:
    external: true
